{{- if and (.Values.webui.mfa).encryptionKey (not (.Values.webui.mfa).existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "janus.mfa.secretName" . }}
  namespace: {{ .Values.janus.namespace }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
type: Opaque
stringData:
  encryptionKey: {{ .Values.webui.mfa.encryptionKey | quote }}
{{- end }}
