{{- if not (.Values.webui.session).existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "janus.session.secretName" . }}
  namespace: {{ .Values.janus.namespace }}
  labels:
    {{- include "janus.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  sessionSecret: {{ (.Values.webui.session).secret | default (randAlphaNum 32) | quote }}
{{- end }}
