"""initial schema

Revision ID: 357cc6440b69
Revises: 
Create Date: 2026-04-21 04:51:26.798505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357cc6440b69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cluster', sa.String(length=100), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('requester', sa.String(length=255), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('denied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_account', sa.String(length=255), nullable=True),
    sa.Column('token_secret', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_cluster'), 'access_requests', ['cluster'], unique=False)
    op.create_index(op.f('ix_access_requests_created_at'), 'access_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_access_requests_name'), 'access_requests', ['name'], unique=True)
    op.create_index(op.f('ix_access_requests_namespace'), 'access_requests', ['namespace'], unique=False)
    op.create_index(op.f('ix_access_requests_phase'), 'access_requests', ['phase'], unique=False)
    op.create_index(op.f('ix_access_requests_requester'), 'access_requests', ['requester'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_name', sa.String(length=255), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event'), 'audit_logs', ['event'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_name'), 'audit_logs', ['request_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('local_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_users_email'), 'local_users', ['email'], unique=True)
    op.create_table('terminal_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_name', sa.String(length=255), nullable=False),
    sa.Column('pod', sa.String(length=255), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terminal_commands_request_name'), 'terminal_commands', ['request_name'], unique=False)
    op.create_index(op.f('ix_terminal_commands_timestamp'), 'terminal_commands', ['timestamp'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_email'), 'user_profiles', ['user_email'], unique=True)
    op.create_table('user_quick_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quick_commands_user_email'), 'user_quick_commands', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quick_commands_user_email'), table_name='user_quick_commands')
    op.drop_table('user_quick_commands')
    op.drop_index(op.f('ix_user_profiles_user_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_terminal_commands_timestamp'), table_name='terminal_commands')
    op.drop_index(op.f('ix_terminal_commands_request_name'), table_name='terminal_commands')
    op.drop_table('terminal_commands')
    op.drop_index(op.f('ix_local_users_email'), table_name='local_users')
    op.drop_table('local_users')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_access_requests_requester'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_phase'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_namespace'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_name'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_created_at'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_cluster'), table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###
