apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: k8s-janus-remote
    app.kubernetes.io/managed-by: {{ .Release.Service }}
