name: DockerHub Description

on:
  push:
    branches:
      - main
    paths:
      - 'DOCKERHUB.md'

jobs:
  update-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: opsmode/k8s-janus
          readme-filepath: ./DOCKERHUB.md
